# Generated by Django 4.2.27 on 2026-02-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
