# Generated by Django 4.2.27 on 2026-02-08 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_providerprofile_is_blocked'),
        ('catalog', '0002_remove_portfoliomedia_portfolio_item_and_more'),
        ('marketplace', '0004_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='target_provider',
            field=models.ForeignKey(blank=True, help_text='If set, only this provider can see the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_requests', to='accounts.providerprofile'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='target_service',
            field=models.ForeignKey(blank=True, help_text='Service that client contacted about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='catalog.service'),
        ),
    ]
