# Generated by Django 4.2.27 on 2026-02-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_add_targeted_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='event_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
