# Generated by Django 4.2.27 on 2026-06-16 20:27

import apps.portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomedia',
            name='file',
            field=models.ImageField(blank=True, upload_to=apps.portfolio.models.portfolio_media_upload_to),
        ),
        migrations.AddField(
            model_name='portfoliomedia',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomedia',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomedia',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='portfoliomedia',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomedia',
            name='file_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='portfoliomedia',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('file', ''), models.Q(('file_url', ''), _negated=True)), models.Q(models.Q(('file', ''), _negated=True), ('file_url', '')), _connector='OR'), name='exactly_one_media_source'),
        ),
    ]
