# Generated by Django 4.2.27 on 2026-06-18 19:35

from django.db import migrations, models
from django.utils import timezone


def populate_plan_codes(apps, schema_editor):
    Plan = apps.get_model('billing', 'Plan')
    for plan in Plan.objects.all():
        name_en_lower = plan.name_en.lower() if plan.name_en else ""
        if plan.price == 0 or 'free' in name_en_lower or 'тегін' in name_en_lower or 'бесплат' in (plan.name_ru or '').lower():
            plan.code = 'free'
        elif plan.price == 9900 or 'pro' in name_en_lower:
            plan.code = 'pro'
        elif plan.price == 49900 or 'enterprise' in name_en_lower:
            plan.code = 'enterprise'
        else:
            base_code = plan.name_en.lower().replace(' ', '_') if plan.name_en else f"plan_{plan.id}"
            code = base_code
            counter = 1
            while Plan.objects.filter(code=code).exclude(id=plan.id).exists():
                code = f"{base_code}_{counter}"
                counter += 1
            plan.code = code
        plan.save()


def migrate_subscription_status(apps, schema_editor):
    Subscription = apps.get_model('billing', 'Subscription')
    now = timezone.now()
    for sub in Subscription.objects.all():
        if not sub.is_active:
            sub.status = 'expired'
        else:
            if sub.end_date < now:
                sub.status = 'expired'
                sub.is_active = False
            else:
                sub.status = 'active'
        sub.save()


def migrate_promocode_discounts(apps, schema_editor):
    PromoCode = apps.get_model('billing', 'PromoCode')
    for promo in PromoCode.objects.all():
        if promo.discount_percent is not None:
            promo.discount_type = 'percentage'
            promo.discount_amount = promo.discount_percent
            promo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price']},
        ),
        migrations.AddField(
            model_name='plan',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='KZT', max_length=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_kz',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='promocode',
            name='eligible_plans',
            field=models.ManyToManyField(blank=True, to='billing.plan'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('failed', 'Failed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(populate_plan_codes, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(migrate_subscription_status, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(migrate_promocode_discounts, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]

