# Generated by Django 4.2.27 on 2026-06-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_discount_amount_and_more'),
        ('accounts', '0004_alter_availability_options_and_more'),
        ('billing', '0004_subscription_nullable_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='BillingWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="Billing provider name (e.g. 'mock')", max_length=50)),
                ('provider_event_id', models.CharField(help_text='Unique event ID from provider, or deterministic dedup key when absent', max_length=200)),
                ('event_type', models.CharField(help_text='Normalized event type: payment_confirmed, payment_failed, payment_cancelled, etc.', max_length=50)),
                ('provider_payment_id', models.CharField(blank=True, help_text="Provider's payment ID from the event payload", max_length=100)),
                ('provider_reference', models.CharField(blank=True, help_text="Provider's reference string from the event payload", max_length=100)),
                ('payload_hash', models.CharField(blank=True, help_text='SHA-256 hex digest of the raw request body for deduplication and audit', max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('safe_summary', models.JSONField(blank=True, default=dict, help_text='Allow-listed safe fields only. Never store secrets, signatures, or card data.')),
                ('error_code', models.CharField(blank=True, help_text='Short machine-readable error code; no sensitive exception text', max_length=100)),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When processing began; used for stale reclaim detection', null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of processing attempts (incremented atomically)')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, help_text='Resolved billing Payment (nullable until resolution succeeds)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code_snapshot', models.CharField(help_text='Immutable code string at redemption time', max_length=50)),
                ('original_amount_snapshot', models.DecimalField(decimal_places=2, help_text='Original plan price at checkout time (Decimal)', max_digits=12)),
                ('discount_amount_snapshot', models.DecimalField(decimal_places=2, help_text='Applied discount amount at checkout time (Decimal)', max_digits=12)),
                ('final_amount_snapshot', models.DecimalField(decimal_places=2, help_text='Final paid amount at checkout time (Decimal)', max_digits=12)),
                ('redeemed_at', models.DateTimeField(help_text='When the redemption was committed (webhook confirmed timestamp)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(help_text='The billing payment this redemption is tied to (one redemption per payment)', on_delete=django.db.models.deletion.PROTECT, related_name='promo_redemption', to='payments.payment')),
                ('promo_code', models.ForeignKey(help_text='The promo code that was redeemed', on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='billing.promocode')),
                ('provider_profile', models.ForeignKey(help_text='Provider who redeemed the promo code', on_delete=django.db.models.deletion.PROTECT, related_name='promo_redemptions', to='accounts.providerprofile')),
                ('subscription', models.ForeignKey(help_text='The subscription activated by this redemption', on_delete=django.db.models.deletion.PROTECT, related_name='promo_redemptions', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['promo_code', 'provider_profile'], name='billing_pro_promo_c_b041b3_idx'), models.Index(fields=['payment'], name='billing_pro_payment_86b7ee_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='promocoderedemption',
            constraint=models.CheckConstraint(check=models.Q(('original_amount_snapshot__gte', 0)), name='promo_redemption_original_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='promocoderedemption',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount_snapshot__gte', 0)), name='promo_redemption_discount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='promocoderedemption',
            constraint=models.CheckConstraint(check=models.Q(('final_amount_snapshot__gte', 0)), name='promo_redemption_final_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='promocoderedemption',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount_snapshot__lte', models.F('original_amount_snapshot'))), name='promo_redemption_discount_lte_original'),
        ),
        migrations.AddIndex(
            model_name='billingwebhookevent',
            index=models.Index(fields=['provider', 'status'], name='billing_bil_provide_bbe373_idx'),
        ),
        migrations.AddIndex(
            model_name='billingwebhookevent',
            index=models.Index(fields=['payment'], name='billing_bil_payment_66a6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='billingwebhookevent',
            index=models.Index(fields=['status', 'processing_started_at'], name='billing_bil_status_e71912_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_billing_webhook_event'),
        ),
    ]
