# Generated by Django 4.2.27 on 2026-01-26 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomedia',
            name='portfolio_item',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
        migrations.DeleteModel(
            name='PortfolioMedia',
        ),
    ]
