# Generated by Django 4.2.27 on 2026-02-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_portfoliomedia_portfolio_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
        ),
    ]
