# Generated by Django 4.2.27 on 2026-02-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity_per_slot',
            field=models.PositiveIntegerField(default=1, help_text='Max simultaneous orders'),
        ),
    ]
