# Generated by Django 4.2.27 on 2026-06-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_service_capacity_per_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
