# Generated by Django 4.2.27 on 2026-06-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_service_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['latitude', 'longitude'], name='service_lat_lng_idx'),
        ),
    ]
