# Generated by Django 4.2.27 on 2026-06-16 21:38

from django.db import migrations, models


def normalize_service_covers(apps, schema_editor):
    Service = apps.get_model('catalog', 'Service')
    ServiceMedia = apps.get_model('catalog', 'ServiceMedia')
    
    for service in Service.objects.all():
        media_qs = ServiceMedia.objects.filter(service=service).order_by('id')
        media_list = list(media_qs)
        covers = [m for m in media_list if m.is_cover]
        
        if len(covers) > 1:
            # Retain the first cover and set others to is_cover=False
            for media in covers[1:]:
                media.is_cover = False
                media.save(update_fields=['is_cover'])
        elif len(covers) == 0:
            # Promote the legacy first media to is_cover=True if it exists
            first_media = media_qs.first()
            if first_media:
                first_media.is_cover = True
                first_media.save(update_fields=['is_cover'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_service_service_lat_lng_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemedia',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicemedia',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicemedia',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicemedia',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(normalize_service_covers, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='servicemedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('service',), name='unique_service_active_cover'),
        ),
    ]
