# Generated by Django 4.2.27 on 2026-02-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_add_targeted_requests'),
        ('accounts', '0002_providerprofile_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('busy', 'Busy (Order)'), ('blocked', 'Blocked (Manual)')], default='blocked', max_length=20)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_slot', to='marketplace.order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.providerprofile')),
            ],
            options={
                'verbose_name': 'Availability Slot',
                'verbose_name_plural': 'Availability Slots',
                'ordering': ['date'],
                'unique_together': {('provider', 'date')},
            },
        ),
    ]
