# Generated by Django 4.2.27 on 2026-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('fraud', 'Fraud'), ('abuse', 'Abuse'), ('inappropriate', 'Inappropriate'), ('other', 'Other')], max_length=20),
        ),
    ]
