# Generated by Django 4.2.27 on 2026-06-18 20:12

from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal

def populate_historical_payment_snapshots(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    for payment in Payment.objects.all():
        try:
            subscription = payment.subscription
            plan = subscription.plan
            plan_code = plan.code or "legacy"
            plan_duration = plan.duration_days or 0
            plan_name_ru = plan.name_ru or "Legacy plan"
            plan_name_en = plan.name_en or "Legacy plan"
            plan_name_kz = plan.name_kz or "Legacy plan"
        except Exception:
            plan_code = "legacy"
            plan_duration = 0
            plan_name_ru = "Legacy plan"
            plan_name_en = "Legacy plan"
            plan_name_kz = "Legacy plan"
            
        payment.plan_code_snapshot = plan_code
        payment.plan_duration_days_snapshot = plan_duration
        payment.plan_name_ru_snapshot = plan_name_ru
        payment.plan_name_en_snapshot = plan_name_en
        payment.plan_name_kz_snapshot = plan_name_kz
        payment.promo_code_snapshot = ""
        
        # original_amount and discount_amount
        payment.original_amount = payment.amount
        payment.discount_amount = Decimal("0.00")
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscription_nullable_dates'),
        ('payments', '0002_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_initialization_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_state',
            field=models.CharField(choices=[('initializing', 'Initializing'), ('ready', 'Ready'), ('failed', 'Failed')], default='initializing', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, help_text='Applied discount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, help_text='Original plan price', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan_code_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan_duration_days_snapshot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan_name_en_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan_name_kz_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan_name_ru_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.promocode'),
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_code_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='mock', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='request_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Final amount to pay', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.RunPython(populate_historical_payment_snapshots, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, help_text='Original plan price', max_digits=12, default=Decimal('0.00')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, help_text='Applied discount', max_digits=12, default=Decimal('0.00')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan_duration_days_snapshot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_profile', 'status', 'created_at'], name='payments_pa_provide_a7dba5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_reference'], name='payments_pa_provide_44281d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', 'status'], name='payments_pa_subscri_b2eaa9_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='payment_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('original_amount__gte', 0)), name='payment_original_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__gte', 0)), name='payment_discount_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__lte', models.F('original_amount'))), name='payment_discount_amount_lte_original'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('idempotency_key__isnull', True), ('idempotency_key', ''), models.Q(('request_fingerprint__isnull', False), models.Q(('request_fingerprint', ''), _negated=True)), _connector='OR'), name='idempotency_key_requires_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('provider_profile', 'idempotency_key'), name='unique_provider_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id__isnull', False), models.Q(('provider_payment_id', ''), _negated=True)), fields=('provider', 'provider_payment_id'), name='unique_billing_provider_payment_id'),
        ),
    ]
