# Generated by Django 4.2.27 on 2026-06-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, help_text='Applied discount', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, help_text='Original plan price', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan_duration_days_snapshot',
            field=models.IntegerField(null=True),
        ),
    ]
