# Generated by Django 4.2.27 on 2026-06-24 03:33

from django.db import migrations, models


def backfill_checkout_state(apps, schema_editor):
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    for tx in PaymentTransaction.objects.all():
        if tx.status == 'pending':
            if tx.checkout_url:
                tx.checkout_state = 'ready'
            else:
                tx.checkout_state = 'idle'
        elif tx.status == 'success':
            tx.checkout_state = 'completed'
        else:
            tx.checkout_state = 'terminal_error'
        tx.save(update_fields=['checkout_state'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_conversion_locked_at_payment_conversion_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_error_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_initialization_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_initialization_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_retry_after',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_state',
            field=models.CharField(choices=[('idle', 'Idle'), ('initializing', 'Initializing'), ('ready', 'Ready'), ('retryable_error', 'Retryable Error'), ('terminal_error', 'Terminal Error'), ('completed', 'Completed')], default='idle', max_length=20),
        ),
        migrations.RunPython(backfill_checkout_state, reverse_code=migrations.RunPython.noop),
    ]

