# Generated by Django 4.2.27 on 2026-06-24 03:34

from django.db import migrations


def cleanup_duplicate_pending_transactions(apps, schema_editor):
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    
    pending_txs = PaymentTransaction.objects.filter(status='pending')
    
    groups = {}
    for tx in pending_txs:
        key = (tx.order_id, tx.provider)
        if key not in groups:
            groups[key] = []
        groups[key].append(tx)
        
    rows_affected = 0
    
    for key, tx_list in groups.items():
        if len(tx_list) <= 1:
            continue
            
        def rank_key(tx):
            has_both = 1 if (tx.provider_payment_id and tx.checkout_url) else 0
            has_provider_id = 1 if tx.provider_payment_id else 0
            created_val = tx.created_at.timestamp() if tx.created_at else 0
            return (has_both, has_provider_id, created_val, str(tx.id))
            
        sorted_txs = sorted(tx_list, key=rank_key, reverse=True)
        winner = sorted_txs[0]
        
        for duplicate in sorted_txs[1:]:
            duplicate.status = 'cancelled'
            duplicate.checkout_state = 'terminal_error'
            duplicate.checkout_error_code = 'paypal_superseded'
            duplicate.save(update_fields=['status', 'checkout_state', 'checkout_error_code'])
            rows_affected += 1
            
    print(f"\n[Data Migration] Duplicate pending transactions resolved: {rows_affected}")


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymenttransaction_checkout_error_at_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_pending_transactions, reverse_code=migrations.RunPython.noop),
    ]

