# Generated by Django 4.2.27 on 2026-06-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_cleanup_duplicate_pending'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('order', 'provider'), name='uniq_pending_payment_tx_order_provider'),
        ),
    ]
